name: CD

on:
  push:
    branches: [ production ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.9.0

        with:
          secret: ${{ secrets.PUSH_TOKEN }}
          approvers: ithank73
          minimum-approvals: 1
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run production
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Deploying application ..."
            composer install -v
            php artisan config:clear
            php artisan route:cache
            php artisan view:clear
            php artisan migrate
            php artisan queue:restart
            npm install
            npm run production
            echo "Application deployed!"

