name: PeopleNJob CD
on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        env:
          COMPOSER: "true"
          NPM_INSTALL: "false"
          NPM_BUILD: "true"
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: COMPOSER,NPM_INSTALL,NPM_BUILD
          script: |
            echo "Current user: $(whoami)"
            cd ~/master
            ./test.sh

