name: PeopleNJob CD

on:
  push:
  workflow_dispatch: # Add manual trigger
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        env:
          COMPOSER: "true"
          NPM_INSTALL: "false"
          NPM_BUILD: "true"
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: COMPOSER,NPM_INSTALL,NPM_BUILD
          script: |
            cd ~/master
            ./test.sh

  manualJob:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps as needed for your manual job
      - name: Run some commands
        run: |
          echo "This job runs only when triggered manually."
