name: PeopleNJob CD

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
#    if: github.event_name == 'push'
    if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        env:
          COMPOSER: ${{ github.event.label.name == 'composer install' }}
          NPM_INSTALL: ${{ github.event.label.name == 'npm install' }}
          NPM_BUILD: ${{ github.event.label }}
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: COMPOSER,NPM_INSTALL,NPM_BUILD
          script: |
            cd ~/master
            ./test.sh

  manualJob:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps as needed for your manual job
      - name: Run some commands
        run: |
          echo "This job runs only when triggered manually."
