<<<<<<< Updated upstream
name: CD

on:
  push:
    branches:
      - production

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: npm run production

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Current user: $(whoami)"
            cd ~/master
            git fetch origin master
            git reset --hard "origin/master"
            # Run your custom update script or other deployment commands here
=======
#name: CD
#on:
#  pull_request:
#    branches:
#      - '*'
#    types:
#      - closed
#  workflow_dispatch:
#jobs:
#  deploy_prod:
#    if: ${{ github.event.pull_request.merged }}
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          token: ${{ secrets.PUSH_TOKEN }}
#      - name: Set up Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: '12.x'
#      - run: npm install
#      - run: npm run production
#      - name: Deploy to production
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_SERVER }}
#          username: ${{ secrets.SSH_NAME }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          port: ${{ secrets.SSH_PORT }}
#          script: |
#            cd ~/master
##            echo "Current user: $(whoami)"
##            ../soft-update.sh
>>>>>>> Stashed changes
