name: Conditional Workflow

on:
  workflow_dispatch:
    inputs:
      TEST:
        description: 'Run echo "true" if checked'
        required: true
        default: 'false'

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run echo based on input
        if: ${{ github.event.inputs.TEST == 'true' }}
        run: echo "true"
      - name: Run echo based on input
        if: ${{ github.event.inputs.TEST != 'true' }}
        run: echo "not true"
